kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    kubeadmConfigPatches:
      - |
        kind: ClusterConfiguration
        apiServer:
          extraArgs:
            "enable-admission-plugins": NodeRestriction
    extraMounts:
      - hostPath: /var/lib/docker
        containerPath: /var/lib/docker
    containerdConfigPatches:
      - |
        [plugins."io.containerd.grpc.v1.cri"]
          enable_nri = true
        [plugins."io.containerd.grpc.v1.cri".containerd]
          snapshotter = "overlayfs"
