apiVersion: v1
kind: Namespace
metadata:
  name: nri-system
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: limit-config
  namespace: nri-system
data:
  limit.conf: |
    {
      "watch_interval": 5,
      "io": {
        "max_disk_bytes": 10485760,
        "bps_limit": 1048576,
        "iops_limit": 5
      },
      "memory": {
        "pods-usage-percent": 20,
        "cache-rss-ratio": 3.5,
        "min-cache-bytes": 10485760
      },
      "log_path": ""
    }
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nri-limit
  namespace: nri-system
spec:
  selector:
    matchLabels:
      app: limit-plugin
  template:
    metadata:
      labels:
        app: limit-plugin
    spec:
      hostPID: true
      containers:
        - name: limit
          image: __PLUGIN_IMAGE__
          imagePullPolicy: Never
          securityContext:
            privileged: true
          command: ["/opt/nri/plugins/limit"]
          volumeMounts:
            - mountPath: /etc/containerd
              name: containerd-config
            - mountPath: /run/containerd
              name: containerd-socket
            - mountPath: /opt/nri/plugins
              name: plugin-dir
            - mountPath: /var/lib/containerd
              name: containerd-root
            - mountPath: /etc/nri/conf.d
              name: nri-conf
          env:
            - name: LIMIT_CONFIG_FILE
              value: /etc/nri/conf.d/limit.conf
      volumes:
        - name: containerd-config
          hostPath:
            path: /etc/containerd
        - name: containerd-socket
          hostPath:
            path: /run/containerd
        - name: plugin-dir
          hostPath:
            path: /opt/nri/plugins
        - name: containerd-root
          hostPath:
            path: /var/lib/containerd
        - name: nri-conf
          projected:
            sources:
              - configMap:
                  name: limit-config
                  items:
                    - key: limit.conf
                      path: limit.conf
