apiVersion: batch/v1
kind: Job
metadata:
  name: __MEMORY_JOB_NAME__
  namespace: default
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: stress
          image: alpine
          command:
            - /bin/sh
            - -c
            - |
              dd if=/dev/zero of=/tmp/cachefile bs=1M count=200 && sync && sleep 10
  backoffLimit: 0
