apiVersion: batch/v1
kind: Job
metadata:
  name: __DISK_JOB_NAME__
  namespace: default
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: stress
          image: alpine
          command:
            - /bin/sh
            - -c
            - |
              dd if=/dev/zero of=/tmp/bigfile bs=1M count=20 && sync && sleep 5
  backoffLimit: 0
