name: Release

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write

env:
  BUILD_PLATFORM: linux/amd64,linux/arm64
  ONLINE_REGISTER: ghcr.io
  ONLINE_REGISTER_USER: ${{ github.actor }}
  ONLINE_REGISTER_PASSWORD: ${{ secrets.PUSH_TOKEN }}


jobs:
  release:
    if: github.repository == 'kcrow-io/plugins'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v3
      with:
        go-version: '1.24'

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to online register
      uses: docker/login-action@v3.0.0
      with:
        username: ${{ env.ONLINE_REGISTER_USER }}
        password: ${{ env.ONLINE_REGISTER_PASSWORD }}
        registry: ${{ env.ONLINE_REGISTER }}

    - name: Build and Push Image
      uses: docker/build-push-action@v5.1.0
      id: docker_build_release
      with:
        context: .
        file: Dockerfile
        push: true
        provenance: false
        platforms: ${{ env.BUILD_PLATFORM }}
        tags: |
          ${{ env.ONLINE_REGISTER }}/${{ github.repository }}:${{ github.ref_name }}
        build-args: |
          GIT_COMMIT_VERSION=${{ env.commitver }}
          GIT_COMMIT_TIME=${{ env.committime }}
          VERSION=${{ github.ref_name }}

    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@v4
      with:
        distribution: goreleaser
        version: '~> v2'
        args: release --clean
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}